Api:
  ConfirmationLevel:
    settings-key: Bcn-ETС-ConfirmationLevel
  GasPriceRange:
    settings-key: Bcn-ETС-GasPriceRange
  GasReserve:
    settings-key: Bcn-ETС-GasReserve
  IsMainNet:
    settings-key: Bcn-ETС-IsMainNet
  MaxGasAmount:
    settings-key: Bcn-ETС-MaxGasAmount
  Db:
    DataConnString:
      settings-key: Bcn-ETС-DataConnString
      types:
        - AzureTableStorage
    LogsConnString:
      settings-key: BcnLogsConnString
      types:
        - AzureTableStorage
  RpcNode:
    ApiUrl:
      settings-key: Bcn-ETС-RpcNodeApiUrl
    ConnectionTimeout:
      settings-key: Bcn-ETС-RpcNodeConnectionTimeout
    EnableTelemetry:
      settings-key: Bcn-ETС-RpcNodeEnableTelemetry
SlackNotifications:
  AzureQueue:
    ConnectionString:
      settings-key: SlackNotificationsConnString
      types:
        - AzureTableStorage
    QueueName:
      settings-key: SlackQueueName
MonitoringServiceClient:
  MonitoringServiceUrl:
    settings-key: MonitoringServiceUrl